/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Application;
import Model.ExtensionFileFilter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Jeffrey
 */
public class ProjectSettings extends javax.swing.JFrame {

    private Map map;
    private Main main;

    public ProjectSettings() {
    }

    /**
     * Creates new form ProjectSettings
     */
    public ProjectSettings(Main main, Map map) {
        initComponents();
        this.map = map;
        this.main = main;
        // Get the size of the screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dim = tk.getScreenSize();
        // Determine the new location of the window
        int x = (dim.width - (this.getSize().width)) / 2;
        int y = (dim.height - (this.getSize().height)) / 2;

        // Center the window
        this.setLocation(x, y);

        // Set the storyname
        tfStoryName.setText(map.getStory().getName());

        // Set the storyimage
        if (map.getStory().getImage() != null) {
            tfStoryImage.setText(map.getStory().getImage().getAbsolutePath());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pProjectSettings = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        lStoryName = new javax.swing.JLabel();
        lStoryImage = new javax.swing.JLabel();
        tfStoryName = new javax.swing.JTextField();
        tfStoryImage = new javax.swing.JTextField();
        bImageBrowse = new javax.swing.JButton();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTitle.setText("Project settings");

        lStoryName.setText("Story name:");

        lStoryImage.setText("Story image:");

        tfStoryImage.setEditable(false);
        tfStoryImage.setMaximumSize(new java.awt.Dimension(6, 20));

        bImageBrowse.setText("Browse..");
        bImageBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImageBrowseActionPerformed(evt);
            }
        });

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProjectSettingsLayout = new javax.swing.GroupLayout(pProjectSettings);
        pProjectSettings.setLayout(pProjectSettingsLayout);
        pProjectSettingsLayout.setHorizontalGroup(
            pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle)
                    .addGroup(pProjectSettingsLayout.createSequentialGroup()
                        .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lStoryName)
                            .addComponent(lStoryImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSave)
                            .addGroup(pProjectSettingsLayout.createSequentialGroup()
                                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfStoryName)
                                    .addComponent(tfStoryImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bImageBrowse)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pProjectSettingsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfStoryImage, tfStoryName});

        pProjectSettingsLayout.setVerticalGroup(
            pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addGap(18, 18, 18)
                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStoryName)
                    .addComponent(tfStoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfStoryImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lStoryImage)
                    .addComponent(bImageBrowse))
                .addGap(18, 18, 18)
                .addComponent(bSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pProjectSettings, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed

        if (!tfStoryName.getText().equals("")) {
            this.map.getStory().setName(tfStoryName.getText());
        } else {
            this.map.getStory().setName(main.getDefaultStoryName());
        }
        
        // Add an astrix if the story has been changed
        if (map.getStory().isSomethingChanged()) {
            main.setTitle("*"+tfStoryName.getText() + " - iStory designer " + Application.getVersion());
        } else {
            main.setTitle(tfStoryName.getText() + " - iStory designer " + Application.getVersion());
        }
        // Refresh the routes panel
        main.getPanelRoutes().refreshList(map.getStory().getRoutes());
        dispose();

    }//GEN-LAST:event_bSaveActionPerformed

    private void bImageBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImageBrowseActionPerformed

        JFileChooser j = new JFileChooser();
        // Add Image filter to the chooser
        j.addChoosableFileFilter(new ExtensionFileFilter(
                new String[]{".JPG", ".JPEG", ".PNG", ".BMP"},
                "Images (*.JPG|JPEG|PNG|BMP)"));

        int dialog = j.showOpenDialog(this);

        // The user selected an imagefile
        if (dialog == JFileChooser.APPROVE_OPTION) {

            File projectFile = j.getSelectedFile();
            map.getStory().setImage(projectFile);
            tfStoryImage.setText(map.getStory().getImage().getAbsolutePath());
        }
    }//GEN-LAST:event_bImageBrowseActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bImageBrowse;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lStoryImage;
    private javax.swing.JLabel lStoryName;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pProjectSettings;
    private javax.swing.JTextField tfStoryImage;
    private javax.swing.JTextField tfStoryName;
    // End of variables declaration//GEN-END:variables
}
