/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Jeffrey
 */
public class ProjectSettings extends javax.swing.JFrame {

    private Map map;

    public ProjectSettings() {
    }

    /**
     * Creates new form ProjectSettings
     */
    public ProjectSettings(Map map) {
        initComponents();
        this.map = map;
        
        // Get the size of the screen
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dim = tk.getScreenSize();
        // Determine the new location of the window
        int x = (dim.width - (this.getSize().width)) / 2;
        int y = (dim.height - (this.getSize().height)) / 2;

        // Center the window
        this.setLocation(x, y);

        // Set the storyname
        tfStoryName.setText(map.getStory().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pProjectSettings = new javax.swing.JPanel();
        lTitle = new javax.swing.JLabel();
        lStoryName = new javax.swing.JLabel();
        tfStoryName = new javax.swing.JTextField();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        lTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lTitle.setText("Project settings");

        lStoryName.setText("Story name:");

        bSave.setText("Save");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pProjectSettingsLayout = new javax.swing.GroupLayout(pProjectSettings);
        pProjectSettings.setLayout(pProjectSettingsLayout);
        pProjectSettingsLayout.setHorizontalGroup(
            pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTitle)
                    .addGroup(pProjectSettingsLayout.createSequentialGroup()
                        .addComponent(lStoryName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSave)
                            .addComponent(tfStoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        pProjectSettingsLayout.setVerticalGroup(
            pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProjectSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitle)
                .addGap(18, 18, 18)
                .addGroup(pProjectSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lStoryName)
                    .addComponent(tfStoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSave)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        getContentPane().add(pProjectSettings, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed

        if (!tfStoryName.getText().equals("")) {
            this.map.getStory().setName(tfStoryName.getText());
        } else {
            this.map.getStory().setName("NewStory");
        }
        
        dispose();

    }//GEN-LAST:event_bSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lStoryName;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pProjectSettings;
    private javax.swing.JTextField tfStoryName;
    // End of variables declaration//GEN-END:variables
}
